---
openapi: 3.0.1
info:
  title: SongKick Demo API V1
  version: v1
paths:
  "/v1/users/users":
    get:
      summary: Listing users
      tags:
      - Users
      parameters:
      - name: sort
        in: query
        required: false
        description: 'Comma-separated list of fields to sort by. Available fields:
          `first_name`, `last_name`, `email`, `updated_at`, `created_at`. Prefix a
          field by `-` to reverse the sort order. For example `foo,-bar` sorts by
          `foo` in ascending order then by `bar` in descending order.'
        schema:
          type: string
      - name: filter[first_name][contains]
        in: query
        required: false
        description: Causes the response to include only records whose `first_name`
          attribute contains the given value as a substring (case-insensitive).
        schema:
          type: string
      - name: filter[last_name][contains]
        in: query
        required: false
        description: Causes the response to include only records whose `last_name`
          attribute contains the given value as a substring (case-insensitive).
        schema:
          type: string
      - name: filter[email][contains]
        in: query
        required: false
        description: Causes the response to include only records whose `email` attribute
          contains the given value as a substring (case-insensitive).
        schema:
          type: string
      - name: filter[created_at][lt]
        in: query
        required: false
        description: Causes the response to include only records whose `created_at`
          attribute is strictly less than the given value.
        schema:
          type: string
      - name: filter[created_at][lte]
        in: query
        required: false
        description: Causes the response to include only records whose `created_at`
          attribute is less than or equal to the given value.
        schema:
          type: string
      - name: filter[created_at][gt]
        in: query
        required: false
        description: Causes the response to include only records whose `created_at`
          attribute is strictly greater than the given value.
        schema:
          type: string
      - name: filter[created_at][gte]
        in: query
        required: false
        description: Causes the response to include only records whose `created_at`
          attribute is greater than or equal to the given value.
        schema:
          type: string
      security:
      - oauth2: []
      responses:
        '200':
          description: listing users
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        password:
          tokenUrl: "/oauth/token"
      scopes: {}
