# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: evan
  password: notnow123
  host: localhost

development:
  <<: *default
  encoding: UTF-8
  database: db/songkick_development

test:
  <<: *default
  database: db/songkick_test

production:
  <<: *default
  database: db/songkick_production
